services:
  supportbot:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Required environment variables
      - BOT_TOKEN=${BOT_TOKEN}
      - STAFFCHAT_ID=${STAFFCHAT_ID}
      - OWNER_ID=${OWNER_ID}
      
      # Optional environment variables with defaults
      - SPAM_CANT_MSG=5
      - SPAM_TIME=300000
      - PARSE_MODE=Markdown
      - ALLOW_PRIVATE=false
      - DIRECT_REPLY=false
      - AUTO_CLOSE_TICKETS=true
      - ANONYMOUS_TICKETS=true
      - ANONYMOUS_REPLIES=true
      - SHOW_AUTO_REPLIED=false
      - SHOW_USER_TICKET=false
      - AUTOREPLY_CONFIRMATION=true
      - CLEAN_REPLIES=false
      - PASS_START=false
      - WEB_SERVER=false
      - WEB_SERVER_PORT=8080
      - WEB_SERVER_SSL_CERT=
      - WEB_SERVER_SSL_KEY=
      - DEV_MODE=true
      - MONGODB_URI=mongodb://mongodb:27017/support
      - USE_LLM=false
      - LLM_API_KEY=
      - LLM_BASE_URL=https://api.openai.com/v1
      - LLM_MODEL=qwen-2.5-7b-instruct
      - LLM_KNOWLEDGE=
      
      # Language environment variables (optional, will use defaults if not set)
      - LANGUAGE_START_COMMAND_TEXT=Welcome in our support chat! Ask your question here.
      - LANGUAGE_FAQ_COMMAND_TEXT=Get this bot at: [github.com](https://github.com/bostrot/telegram-support-bot)
      - LANGUAGE_HELP_COMMAND_TEXT=*Available commands:* /help /faq /id
      - LANGUAGE_CONFIRMATION_MESSAGE=Thank you for contacting us. We will answer as soon as possible.
      
      # Autoreply and categories (JSON format, optional)
      - AUTOREPLY=
      - CATEGORIES=

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./.tmp/mongodb_data:/data/db 

  # mongodb web interface
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password  

volumes:
  mongodb_data:
