services:
  supportbot:
    build: .
    restart: unless-stopped
    environment:
      # Required environment variables
      BOT_TOKEN: ${BOT_TOKEN}
      STAFFCHAT_ID: ${STAFFCHAT_ID}
      OWNER_ID: ${OWNER_ID}
      DEV_MODE: ${DEV_MODE:-false}
      LANGUAGE_START_COMMAND_TEXT: ${LANGUAGE_START_COMMAND_TEXT:-Welcome in our support chat! Ask your question here.}

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./.tmp/mongodb_data:/data/db 

  # mongodb web interface
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password  

volumes:
  mongodb_data:
